src/components/Header/styles.scss

[FIX] Alerts should be on top of everything else

---

src/lib/main.js

An `await` was missing when assigning the room agent to `state`.

[FIX] Agent assignment

---

src/components/Tooltip/styles.scss

[FIX] Tooltips should be on top of messages and alerts

---

src/components/Header/styles.scss

[FIX] Header title overflow

---

src/components/Composer/index.js

When `value` prop is `null` or `undefined`, `value.length` fails.

[FIX]  Composer.shouldComponentUpdate() error

---

src/components/Message/styles.scss

closes #178 
There was a wrong property value on the message CSS.

[FIX] messages not breaking

---

src/components/App/index.js

This PR aims to avoid an extra call to `store.setState()` on page unload.

[FIX] Remove visibility listener on unload page

---

src/components/Menu/styles.scss
src/components/Modal/styles.scss
src/styles/colors.scss

Closes #192.
Changed the `overlay background color` of the Modal component, applying the same color used in the popup.

Modal background color

---

src/components/helpers.js
src/lib/main.js
src/routes/Chat/container.js
src/routes/Chat/room.js

Closes #190.
The number of unread messages was counting message types that should not be rendered, such as `livechat_navigation_history`, etc.

[FIX] Unread messages counter

---

src/routes/Chat/container.js

When a real agent is used to send triggers messages and a new conversation is started, the same agent needs to be assigned to the new livechat room.
Otherwise, the routing method may get another agent in the queue. 
Related to:
https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/73
https://github.com/RocketChat/Rocket.Chat/pull/14103

Pass triggered agent when getting a new room

---

package.json
src/components/App/index.js
src/lib/main.js
src/lib/room.js
src/routes/Chat/component.js
src/routes/Chat/container.js
src/store/index.js
yarn.lock

We changed the `endpoint` to get a new Livechat room, allowing to pass the` agentId` that was used to send trigger messages. Then, if the guests send a message and start a new conversation, the agent that will respond to the chat will be the same one that sent the trigger messages.

Update JS/SDK version

---

src/routes/Register/container.js

Closes #196.
Since the Livechat Router is not based on store/state, when a user is registered through the Livechat API, the registration form needs to detect this change and redirect it to `Chat` container.

Close registration form when registering the user through the Livechat API

---

package.json
src/components/Messages/Message/index.js
src/lib/room.js
src/lib/threads.js
src/routes/Chat/container.js
src/widget.js
yarn.lock

Before the implementation of threads, the payload of `reply` and `quoted` messages were equal, but now the reply messages are not sent as attachments anymore, so we need to fetch the parent message from the server and then render it as an attachment.

Support thread messages as attachments

---

src/widget.js

Problem was with `100vw`, chrome was not able to get it correctly, so as this converts to `100%` in the end so changed it to 100% only.

[FIX] Widget height on mobile browsers

---

src/components/Messages/MessageList/index.js

There was a bug when rendering trigger messages, the rendering was broken, look:
After replacing the key field from `ts` to `_id`, everything works fine again.

[FIX] Replace messages list key prop

---

src/lib/hooks.js

Related to https://github.com/RocketChat/Rocket.Chat/pull/14970.
We need to send the navigation history even if there is no room yet created.
This is the same behavior we had on the old Livechat widget.

[FIX] Sends the navigation history even when there is no room created

---

preact.config.js

Closes #289 
Closes #290 
When the `Rocket.Chat` runs in a subfolder, the Livechat chunk files aren't loaded because of the current Webpack config.
I'm sharing a few screenshots showing the test of running Rocket.Chat in a subfolder:
Old **index.html:**
New **index.html(relative path):**

[FIX] Support Webpack relative output path

---

src/components/App/index.js
src/lib/hooks.js
src/lib/main.js
src/widget.js

Closes #187
New method to minimize the widget:
```
RocketChat(function() {
this.minimizeWidget();
});
```
New method to maximize the widget:
```
RocketChat(function() {
this.maximizeWidget();
});
```

[NEW] Add new API methods to minimize / maximize the Widget

---

src/routes/Register/component.js

Closes #282 
The validation method was not being fired when the Registration Form fields change from the store.
When external users call the API methods, such as `setGuestEmail` or `setGuestName`, the internal state changes, but the `Start Chat` button keeps disabled because of the validation method wasn't be fired.

[FIX] Registration Form changes not being detected

---

src/routes/ChatFinished/container.js

Closes #303 
Related to https://github.com/RocketChat/Rocket.Chat/pull/15577
Adds a new setting to set a custom text message which will be displayed in the `Chat Finished` container/component.

[NEW] Add setting to display a custom chat finished text

---

src/lib/customFields.js
src/lib/room.js
src/routes/Chat/container.js

- Fix the `onChatStarted` call, that was being called in the wrong place. Due to that, the callback method was being triggered every time de widget got to the room, even when the room already existed.
- Fix the logic when starting the `CustomFields` lib. Since the user is stored in the local storage, when the script was reloaded the `Custom Fields` lib was not being started again.

[FIX] API method calls

---

src/components/helpers.js

The unread messages alert was being displayed when receiving the `livechat-close` system message, as shown below:

[FIX] Unread messages alert

---

src/lib/locale.js

One more issue detected after upgrading the `date-fns` package version.
The new version has changed some old supported languages and also added new ones.

[FIX] Date-fns language import

---

src/components/App/index.js
src/lib/parentCall.js
src/routes/Chat/container.js
src/widget.js

This PR allows registering a new callback on the widget API to notify the client when the Livechat Service is offline(`no-agent-online`).
Also, it will be possible to auto-emitter the callback events when the event name is a valid callback, such as the `no-agent-online`.

[NEW] Add Service Offline callback

---

src/i18n/de.json

This pull request corrects the German upper and lower case for the label of finished chat.

Corrected German title for  finished chat

---

src/components/helpers.js
src/lib/room.js
src/routes/Chat/container.js
src/store/Store.js
src/store/index.js
widget-demo.html

When the Widget is running in multiples tabs(same origin) and the user interaction with it, even though we store the data(and the state) of the widget in the `localStorage`, the changes don't reflect on other tabs than the one on which the user is chatting.
Another example: In case the livechat fired trigger messages, the agent fetched from the server may not be the same since the state of each widget has not been synchronized between all open tabs, which provides a very bad user experience.
To fix this wrong behavior, this implementation relies on the `onStorage` event handler for processing storage events and keep the state of each open widget synchronized.

[NEW] Add Cross-tab communication on the same origin

---

src/lib/hooks.js
src/lib/room.js
src/lib/triggers.js
src/routes/Chat/container.js
src/routes/Register/container.js
src/routes/SwitchDepartment/container.js

The trigger messages are not persistent messages, so they're displayed on the client-side only.
They were being removed from the `localStorage` after a new conversation started, but now they'll continue to be displayed after a visitor starts chatting, maintaining the expected behaviour of this feature.
Also, other improvements are part of this PR, such as reducing the number of unnecessary calls to the `loadConfig` method, which was being called just to reload the `state` of the local configuration.

[IMPROVE] Keep trigger messages after the conversation starts

---

src/lib/hooks.js
src/lib/room.js
src/lib/triggers.js
src/widget.js

Adds the `setAgent` method which allows setting the default agent before the visitor starts chatting.
Also, since the agent who sends trigger messages is the same who will serve the conversation, the store prop `triggerAgent` has been renamed/unified to `defaultAgent` prop.

[NEW] Add new API method the set the default Agent before chatting

---

src/components/helpers.js
src/routes/LeaveMessage/component.js
src/routes/LeaveMessage/container.js

CLOSES #396 
Improvements on the Offline Message Form:
- Show a modal message after the message is sent successfully instead of an alert on the top of the form. The previous alert was not clear enough and users where clicking on the submit button several times. Now the users will get a modal alert like shown below:
- We're now resetting the form after the message is sent;
- We're now sharing the `hostname` from where the message has been sent;

Improvements on sending offline messages

---

src/lib/uiKit.js

Interaction with UIKit blocks were sending POST requests to `[HOST]/api/v1/apps/ui.interaction/[APP_ID]`, when the correct route is `[HOST]/api/apps/ui.interaction/[APP_ID]`

[FIX] UiKit interaction call

---

webpack.config.js

It transpiles `widget.js` to ES5 to be parseable by IE11.

[FIX] Transpile widget.js with Babel

---

CHANGELOG.md
package.json
src/lib/uiKit.js
webpack.config.js

[FIX] UiKit interation using header as autorization (#483)
[FIX] Transpile widget.js with Babel

Release 1.7.2

---

webpack.config.js

It was a problem between emoji-mart and webpack, just some configurations in webpack file was necessary.

[FIX] Emoji picker not rendering

---

src/components/uiKit/message/ActionsBlock/styles.scss

[FIX] UIKit ActionsBlock layout for smaller screen devices

---

src/components/Emoji/shortnameToUnicode.js
src/components/Messages/MessageText/emoji.js
src/components/Messages/MessageText/index.js
src/components/Messages/MessageText/markdown.js

Rendering the emojis before HTML (transformed by markdown-it plugin)

[FIX] Rendering emojis before transform markdown into HTML.

---

src/components/Messages/MessageContainer/styles.scss

[FIX] Visitor's messages are not aligned properly on Mozilla Firefox

---

src/components/App/index.js

After maximizing the window of the livechat widget (pop-out) and closing it again, the livechat cannot be restored.
Also, a page refresh does not help.

[FIX] Livechat window cannot be restored in popout mode

---

src/routes/Register/component.js

The livechat registration form is no longer validating mandatory custom fields.

[FIX] Registration form is no longer validating mandatory custom fields.

---

package.json
src/components/Composer/index.js
src/components/Messages/MessageText/markdown.js
yarn.lock

This PR solve a Cross Site Scripting (XSS) vulnerability.
Messages and composer are reading HTML code, so it's necessary a `sanitizer` to strip out everything that contains dangerous HTML.
Package: [DOMPurify](https://github.com/cure53/DOMPurify) (same of RC)
https://user-images.githubusercontent.com/2493803/109339791-e7fb9300-7846-11eb-9777-d4bdfca6f4ac.mp4

[FIX] Add sanitizer to prevent XSS attacks

---

src/components/Footer/styles.scss
src/routes/Chat/component.js
src/routes/Chat/styles.scss

Added hover effect for changing the colour of the icon and link on MessageBox in omni channel Livechat.
Additional context :
https://user-images.githubusercontent.com/56799414/111767984-5a531680-88cd-11eb-8695-9abb526fc3cb.mov
Issue solve:
#565

[IMPROVE] add hover effect 

---

src/components/Tooltip/index.js

[FIX] issue #376 
While clicking on notification toggle button, now tooltip value is also updating on UI with its state .
Additional context :
https://user-images.githubusercontent.com/56799414/111919765-a3fc5680-8ab1-11eb-9025-83eaf323c73b.mov

[FIX] sound notification on/off

---

src/components/Calls/CallIFrame.js
src/routes/Chat/component.js

https://user-images.githubusercontent.com/51796498/129451569-56b6ac1e-35d9-476b-a9af-e23ffbd63592.mp4

[NEW] Handle endCall and expandView control buttons

---

src/components/Calls/CallNotification.js
src/lib/room.js

Earlier on declining the call, the visitor was only updating the status in the database and not notifying the agent due to which the agent on the meet page still waited for the visitor to join after the decline event.
https://user-images.githubusercontent.com/51796498/129457306-f37e7bef-e24b-47dc-afc6-71f6354c0e39.mp4
https://user-images.githubusercontent.com/51796498/129470189-1a27ff1e-d9ac-4360-92a6-ef5db1fc32eb.mp4
Uses [#144](https://github.com/RocketChat/Rocket.Chat.js.SDK/pull/144)

[NEW] Notify agent on call decline

---

src/components/Calls/CallIFrame.js
src/components/Calls/CallNotification.js
src/components/Calls/JoinCallButton.js
src/components/helpers.js
src/lib/room.js

If an agent calls the visitor and the visitor is accessing the live chat widget from mobile, then after accepting the call, webrtc-call will start in a new tab instead of starting the call in iframe. And also add join call button will be there in  livechat widget, which can be used to join the call, if visitor by mistake close the webrtc-call tab.

[NEW] WebRTC-call in new tab for mobile devices

---

src/components/Messages/MessageText/markdown.js
src/lib/triggers.js
src/routes/TriggerMessage/component.js
src/routes/TriggerMessage/container.js
src/routes/TriggerMessage/styles.scss
src/store/Store.js
src/widget.js

Calculate the size for iframe wrapper element and adjust when triggered messages appear.

[FIX] Iframe overlay

---

src/api.js
src/components/App/index.js
src/components/helpers.js

- Create `rc_is_widget` cookie to identify when a request is coming thorugh widget
- Added Secure & SameSite policies for when the widget is served through HTTPS and (probably) in a different domain

[IMPROVE] Add cookie to identify widget calls

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-checker.yml

Every PR should follow the same naming convention we have on Rocket.Chat's main repo.

Chore: Add PR title check

---

src/components/App/index.js

Turn off Omnichannel from Admin -> Omnichannel
The start an omnichannel conversation from anywhere like LiveChat, API, app, etc. The simplest way would be to go to `{serverUrl}/livechat` and send a message.
**Before:** The conversation will be started
**Expected Behaviour:** An error should be thrown stating that omnichannel is disabled

[FIX] Hide Livechat if Omnichannel is disabled

---

CHANGELOG.md
package.json
src/components/App/index.js

[FIX] Hide Livechat if Omnichannel is disabled #671

Release 1.11.1

---

src/components/Composer/index.js
src/routes/Chat/container.js

close https://github.com/RocketChat/Rocket.Chat.Livechat/issues/605

[FIX] IME not working properly

---

src/lib/hooks.js
src/lib/main.js
src/lib/room.js
src/store/Store.js
src/store/index.js
src/widget.js
widget-demo.html

Depends on https://github.com/RocketChat/Rocket.Chat/pull/24162
Please note: Since Business Units is an Enterprise feature, hence this new method will only work if you have a valid enterprise license of Rocket.Chat

[NEW] Introduce Widget API method to manage Business Units

---

src/components/Button/styles.scss
src/components/ButtonGroup/styles.scss
src/components/Form/mixins.scss
src/components/Header/styles.scss
src/components/Menu/styles.scss
src/components/Messages/MessageContainer/styles.scss
src/components/Messages/MessageContent/styles.scss
src/components/Messages/MessageTime/styles.scss
src/components/Screen/styles.scss
src/components/uiKit/message/ButtonElement/styles.scss
src/styles/grid.scss

It removes a lot of deprecation warning messages when building.

Chore: Replace `a / b` with `math.div(a, b)` on SCSS files
