RocketChat/Rocket.Chat.Livechat

- src/components/Typing/index.js
- src/components/Typing/story.js
- src/components/Typing/style.scss
- src/styles/helpers.scss
> [NEW] three dots

- src/components/header/style.scss
- src/routes/profile/index.js
I'm seeing these problems when running `npm run dev`
> Fixing styles imports and button component when running 'npm run dev'

- .gitignore
- package.json
> Adding code coverage to npm scripts

- package.json
- src/components/Tooltip/index.js
- src/components/Tooltip/stories.js
- src/components/Tooltip/styles.scss
> [NEW] Floating Tooltips

- src/components/Menu/index.js
- src/components/Menu/stories.js
- src/components/Menu/styles.scss
> [NEW] Menus

- src/components/app.js
- src/lib/customFields.js
- src/lib/triggers.js
This PR adds the initial implementation supporting Livechat custom fields.
Custom fields will be used in most cases by the Livechat API / interface that is not yet implemented.
> [NEW] Add support for custom fields

- src/components/Screen/index.js
- src/components/Tooltip/index.js
- src/i18n/default.json
- src/i18n/en.json
- src/i18n/pt.json
> [NEW] Add Tooltip component to header buttons

- src/components/Alert/index.js
- src/components/Alert/stories.js
- src/components/Alert/styles.scss
- src/components/Header/index.js
- src/components/Header/stories.js
- src/components/Header/styles.scss
- src/components/Screen/index.js
- src/components/Screen/stories.js
- src/icons/close.svg
- src/store/index.js
> Add Alert component

- src/components/Avatar/index.js
- src/components/Avatar/stories.js
- src/components/Avatar/styles.scss
- src/components/Header/index.js
- src/components/Header/stories.js
- src/components/Header/styles.scss
- src/components/Screen/index.js
- src/components/Screen/stories.js
- src/components/Screen/styles.scss
- src/components/StatusIndicator/index.js
- src/components/StatusIndicator/stories.js
- src/components/StatusIndicator/styles.scss
- src/routes/Chat/container.js
> Agent's custom fields

- src/components/Header/index.js
- src/components/Header/styles.scss
> [FIX] Alert positioning

- src/components/Composer/index.js
- src/routes/Chat/component.js
> Show composer actions only if it has text

- src/components/Alert/styles.scss
- src/components/Button/index.js
- src/components/Button/styles.scss
- src/components/ChatButton/styles.scss
- src/components/Composer/styles.scss
- src/components/Footer/styles.scss
- src/components/Header/styles.scss
- src/components/TypingIndicator/styles.scss
- src/styles/helpers.scss
This should re-enable click events triggered by clicks on the top.
> [FIX] Clickable region for buttons

- src/lib/constants.js
- src/lib/main.js
- src/lib/triggers.js
- src/routes/Chat/container.js
- src/routes/Chat/room.js
- src/store/index.js
> [FIX] Show badges on trigger messages

- package.json
- preact.config.js
- widget-demo.html
Changed the output folder path on the server side.
> Release Livechat client as a community feature

- .circleci/config.yml
- CHANGELOG.md
- src/routes/Chat/container.js
- src/routes/Chat/room.js
Closes #193.
This PR adds some fixes related to `connecting` status.
> [FIX] Connecting status

- src/routes/Register/component.js
> Fix scroll on Register Form

- src/routes/LeaveMessage/component.js
- src/routes/LeaveMessage/container.js
Related to https://github.com/RocketChat/Rocket.Chat/pull/13775/files.
> Add department field on Offline Message Form

- src/components/helpers.js
- src/routes/LeaveMessage/component.js
- src/routes/LeaveMessage/container.js
- src/routes/Register/component.js
Sort department list by name on select components.
> Sort departments on Forms

- .gitignore
- src/components/App/index.js
- src/lib/hooks.js
- src/lib/language.js
- src/lib/locale.js
- src/widget.js
> [NEW] Add setLanguage method in livechat api methods

- src/widget.js
Reverts RocketChat/Rocket.Chat.Livechat#222
> Revert "[FIX] Widget height on mobile browsers"

- src/lib/api.js
- src/lib/room.js
- src/lib/triggers.js
- src/widget.js
This PR adds two new API events:
- onAssignAgent
- onAgentStatusChange
> Adds new API events

- src/components/Messages/MessageText/markdown.js
> [FIX] Make message markdown links open externally

- package.json
Update the SDK dependency to the latest alpha version(29).
> Update SDK alpha version

- src/routes/ChatFinished/stories.js
> [CHORE] Add custom messages to Storybook (ChatFinished component). (#310)

- src/components/Messages/MessageTime/index.js
- src/routes/ChatFinished/stories.js
Fix some issues when running **Storybook**.
> [FIX] Storybook

- src/components/Messages/Message/index.js
- src/components/Messages/MessageAvatars/stories.js
> [FIX] Livechat guest avatar using name instead of username

- src/components/App/index.js
- src/components/Messages/Message/index.js
- src/components/Screen/index.js
- src/components/Sound/index.js
- src/components/helpers.js
- src/lib/room.js
- src/store/Store.js
- src/widget.js
- widget-demo.html
When the Livechat widget is running in multiple tabs and a new message arrives, all tabs are playing the sound notification at the same time, which brings a very annoying experience for Livechat users.
> [FIX] Widget playing multiple sound notifications(Multiple tabs)

- src/routes/SwitchDepartment/container.js
> [FIX] Loading should be false when department switch is confirmed

- src/routes/SwitchDepartment/component.js
Fix Change Department the start chat button is disable with handler validate check nonEmpty function error.
> fix Start chat disable with handler validate error

- src/routes/LeaveMessage/component.js
> [FIX] Error when displaying the LeaveMessage screen

- src/lib/uiKit.js
Fix the UIKit interaction request again
> Regression: UiKit interaction request

- src/routes/LeaveMessage/component.js
- src/routes/SwitchDepartment/component.js
> [FIX] Select input field not working issue

- src/store/Store.js
https://user-images.githubusercontent.com/2493803/107070024-82753300-67c1-11eb-9b07-ef4e15ddc99b.mp4
https://user-images.githubusercontent.com/2493803/107070130-a6387900-67c1-11eb-91a9-8794973ccf5e.mp4
https://user-images.githubusercontent.com/2493803/107071511-8d30c780-67c3-11eb-9afc-7890fb23d557.mp4
https://user-images.githubusercontent.com/2493803/107081804-046d5800-67d2-11eb-810f-09255e4b8fb6.mp4
https://user-images.githubusercontent.com/2493803/107087837-d3455580-67da-11eb-8edf-cc049d3c2d94.mp4
> [FIX] Livechat widget on mobile version is not working correctly with multiple instances

- src/components/Messages/MessageText/markdown.js
prevent target attribute from being removed by sanitizer
> [IMPROVE] Open links in another tab on Livechat widget

- src/styles/index.scss
- src/widget.js
Fixes #572
Inspired from https://github.com/RocketChat/Rocket.Chat.Livechat/pull/619
> Fixes #572 - Body styles getting overridden

- src/lib/hooks.js
> [FIX] LoadConfig after registering guest

- package.json
- src/components/helpers.js
- src/lib/hooks.js
- src/lib/random.js
- src/lib/room.js
- src/lib/threads.js
- src/lib/triggers.js
- src/routes/Chat/container.js
- src/routes/LeaveMessage/container.js
- src/routes/SwitchDepartment/container.js
- src/store/Store.js
- src/store/index.js
- yarn.lock
After reading the report on https://app.clickup.com/t/1nnnqte i suggest improving the token generation code so that even if we're using sha256 on the token generation pipeline, the possibility of brute forcing the tokens becomes negligible.
> [IMPROVE] Change logic to generate token on Live Chat

- CHANGELOG.md
- package.json
- src/components/Composer/index.js
- src/components/Messages/MessageText/markdown.js
- src/components/helpers.js
- src/routes/Chat/container.js
- yarn.lock
[FIX] IME not working properly #674
> Release 1.11.2

- src/components/Form/index.js
- src/lib/email.js
Using the same code from https://github.com/RocketChat/Rocket.Chat/pull/23816 as requested by https://github.com/RocketChat/Rocket.Chat.Livechat/pull/563
> [IMPROVE] Centralized e-mail validation under a library function

- CHANGELOG.md
- package.json
> Release 1.13.1

- src/components/App/App.js
- src/lib/triggers.js
Tested all 3 of the triggers, they send messages to the user based on configured values correctly.
> [FIX] Broken triggers

- CHANGELOG.md
- package.json
- src/components/App/App.js
- src/components/App/index.js
- src/components/Form/index.js
- src/lib/connection.js
- src/lib/triggers.js
[FIX] Translations sync with admin config (#713)
[FIX] Broken triggers (#712)
[FIX] setting e-mail validation to RFC regex as the standard (#709)
> Release 1.13.3
